# Generated by Django 5.2.8 on 2025-11-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
