from post.models import Post
from django.core.management.base import BaseCommand


class Command(BaseCommand):
    help="This command inserts post data"
    
    def handle(self, *args: any, **options: any):
        titles = [
            "Getting Started with Python for Beginners",
            "How to Build Your First Django Project",
            "Top 20 Python Interview Questions for Freshers",
            "A Complete Guide to REST API Development",
            "How to Deploy a Django App on AWS",
            "Mastering Object-Oriented Programming in Python",
            "SQL vs NoSQL — Which One Should You Learn?",
            "Understanding HTML, CSS, and JavaScript for Full Stack Development",
            "10 Best Mini Projects for Computer Science Students",
            "How to Build a Blog Website Using Django",
            "Top 10 Tips to Crack Your First IT Job",
            "How to Create Virtual Environment in Python",
            "Debugging Techniques Every Developer Should Know",
            "The Future of Artificial Intelligence and Machine Learning",
            "Roadmap to Become a Python Full Stack Developer",
            "How to Use Git and GitHub Like a Pro",
            "Creating User Authentication in Django",
            "Why Data Structures and Algorithms Matter in Coding",
            "Top 10 Websites to Practice Coding for Free",
            "Introduction to Cloud Computing for Beginners",
            "How to Connect Django with MySQL Database",
            "Deploying Applications with Docker — Step by Step",
            "Understanding API Integration with Python",
            "How to Build a To-Do App Using Django",
            "Why Developers Should Learn Linux",
            "Mastering Python List, Tuple, Set, and Dictionary",
            "How to Build a Chatbot Using Python",
            "Real-Time Applications of Machine Learning",
            "How to Improve Your Problem-Solving Skills for Coding",
            "Difference Between Frontend and Backend Development",
            "Top 20 Django Interview Questions and Answers",
            "How to Use Pandas for Data Analysis in Python",
            "10 Tips to Build an Attractive Resume for Software Jobs",
            "Why Competitive Programming Helps in Placements",
            "Understanding MVC and MVT Architecture",
            "How to Build Portfolio Projects for GitHub",
            "An Introduction to Web Scraping with Python",
            "How to Host Your Website for Free",
            "Top 10 Python Libraries Every Developer Should Know",
            "Complete Guide to Django Admin Customization",
            "What is CI/CD? — A Beginner Friendly Explanation",
            "How to Send Email Using Python",
            "Mastering Loops and Functions in Python",
            "How to Prepare for a Software Job as a Mechanical Engineer",
            "Step-by-Step Roadmap to Crack IT Jobs in 2025",
            "Best YouTube Channels to Learn Programming",
            "Understanding JSON and XML in Real Projects",
            "The Power of Automation Using Python",
            "How to Build Your Own Portfolio Website"
        ]

        contents = [
            "Python is one of the most beginner-friendly programming languages. In this blog, we explore how to install Python, write your first program, and understand core concepts like variables, loops, and functions.",
            "Django is a powerful full-stack web framework. Here we walk you through setting up a Django project, creating apps, connecting templates, and understanding the MTV architecture.",
            "Preparing for Python interviews can feel overwhelming. This content covers the most important questions with clear explanations and examples to help freshers crack technical rounds confidently.",
            "APIs act as a bridge between applications. In this blog, we explain how REST APIs work, how to build them using Django Rest Framework, and how to test them using Postman.",
            "AWS provides secure hosting for applications. Here you will learn EC2, RDS, S3, and how to deploy a Django application with proper configuration and scaling.",
            "Object-oriented programming brings structure and reusability to code. This post simplifies concepts like classes, objects, inheritance, polymorphism, and abstraction with examples.",
            "SQL and NoSQL databases are used widely. We highlight the differences, advantages, and when to choose each based on scalability, structure, and performance.",
            "Full stack developers must know HTML, CSS, and JavaScript. This blog helps you understand the role of each and how they work together to create interactive web pages.",
            "Finding a perfect mini-project is key for learning. Here we list 10 practical projects with full explanation that students can build for portfolio and learning.",
            "This blog explains how to build a full blogging website in Django using models, views, templates, authentication, and media uploads step-by-step.",
            "Getting your first IT job requires smart preparation. Here are 10 proven tips to improve résumé, portfolio, LinkedIn profile, and interview performance.",
            "Virtual environments help isolate dependencies. We show how to create, activate, and manage virtual environments using venv and pip.",
            "Debugging is a critical skill for developers. This article explains debugging cracks, breakpoints, logs, and common debugging tools in Python.",
            "AI and ML are transforming industries worldwide. This blog explores future trends, real-world applications, and why learning ML can be a powerful career move.",
            "This guide shows a full roadmap to become a Python full-stack developer — from basics to advanced frameworks, DevOps, cloud, and deployment.",
            "Git and GitHub are mandatory in IT industry. We explain how to commit, push, pull, create branches, resolve merge conflicts, and maintain public repositories.",
            "Django authentication makes it easy to manage users. We walk through registration, login, logout, password reset, and custom user models.",
            "Data structures and algorithms help you build efficient programs. This blog explains time complexity, arrays, linked lists, stacks, queues, and trees clearly.",
            "Practicing coding daily is the best habit. Here we list the top 10 free platforms with pros, cons, and useful beginner tips.",
            "Cloud computing powers global services. This blog explains computing models, cloud providers, pricing, storage, and career opportunities for beginners.",
            "MySQL database works smoothly with Django. Here we teach installation, configuration, creating models, applying migrations, and running queries.",
            "Docker helps developers ship applications easily. This guide explains containerization, images, containers, volumes, and deployment workflows.",
            "Python makes API integration simple. This content explains sending HTTP requests, authentication, JSON parsing, and integration patterns.",
            "In this blog you will build a fully working To-Do application using Django with database, CRUD operations, bootstrap UI, and authentication.",
            "Linux is powerful for developers. Here we cover basic commands, file system navigation, package installation, and shell scripting.",
            "Understanding lists, tuples, sets, and dictionaries is essential in Python. This blog provides examples and use-cases to master them.",
            "Chatbots are trending. This content walks through API models, NLP basics, and building a chatbot using Python libraries.",
            "Machine learning powers smart systems. We explain supervised, unsupervised and reinforcement learning with simple real-life examples.",
            "Coding is not just skill — it’s mindset. Here we share strategies to improve logical thinking, pattern recognition, and debugging approach.",
            "Frontend works on UI while backend manages logic. This blog clearly compares frontend vs backend skills, tools, frameworks, and salaries.",
            "This post includes the top Django interview questions and clear answers to help freshers shine in technical interviews.",
            "Pandas is the most powerful Python data analysis library. We explain DataFrames, reading CSV files, cleaning, grouping, and plotting.",
            "A great resume is key for job selection. This content explains formatting, skills section, achievements, and how to stand out as fresher.",
            "Competitive coding sharpens logic and confidence. This post explains benefits, platforms, and daily practice routine.",
            "MVC and MVT are architectural patterns. Here we break down both rules, diagrams, and how Django fits into MVT structure.",
            "GitHub portfolio helps recruiters notice you. This blog shows how to upload projects, write README, and showcase skills professionally.",
            "Web scraping extracts useful information from websites. We demonstrate scraping using BeautifulSoup and storing results in database.",
            "Hosting a website for free is possible. We show free hosting platforms like Netlify, GitHub Pages, and Firebase with steps.",
            "Python has endless libraries for developers. This article lists the 10 most important libraries with real-time use cases.",
            "Django Admin can be deeply customized. This content teaches how to add search, filters, inline models, pagination, and permissions.",
            "CI/CD automates development pipeline. This blog explains continuous integration, continuous delivery, and integration tools.",
            "Sending emails using Python is very easy. Here we share a complete example using smtplib and Django email backend.",
            "Loops and functions form the core of programming. This blog explains how they work with interactive examples.",
            "Many mechanical engineers switch to IT. This article shares a step-by-step guide, roadmap, and success stories.",
            "Cracking IT jobs in 2025 needs smart preparation. This content covers skills, portfolio, networking and interview strategies.",
            "YouTube is a great learning tool. Here we list the best channels for learning Python, AI, and web development.",
            "JSON and XML are used widely. This blog explains format, parsing, validation, and where each is used in projects.",
            "Automation saves time and effort. This post explains automating reports, emails, testing, and scripts using Python.",
            "Portfolio website builds your personal brand. We show how to build and host a professional portfolio step-by-step."
        ]

        img_urls=[
            "https://picsum.photos/id/1/800/400",
            "https://picsum.photos/id/2/800/400",
            "https://picsum.photos/id/3/800/400",
            "https://picsum.photos/id/4/800/400",
            "https://picsum.photos/id/5/800/400",
            "https://picsum.photos/id/6/800/400",
            "https://picsum.photos/id/7/800/400",
            "https://picsum.photos/id/8/800/400",
            "https://picsum.photos/id/9/800/400",
            "https://picsum.photos/id/10/800/400",
            "https://picsum.photos/id/11/800/400",
            "https://picsum.photos/id/12/800/400",
            "https://picsum.photos/id/13/800/400",
            "https://picsum.photos/id/14/800/400",
            "https://picsum.photos/id/15/800/400",
            "https://picsum.photos/id/16/800/400",
            "https://picsum.photos/id/17/800/400",
            "https://picsum.photos/id/18/800/400",
            "https://picsum.photos/id/19/800/400",
            "https://picsum.photos/id/20/800/400",
            "https://picsum.photos/id/21/800/400",
            "https://picsum.photos/id/22/800/400",
            "https://picsum.photos/id/23/800/400",
            "https://picsum.photos/id/24/800/400",
            "https://picsum.photos/id/25/800/400",
            "https://picsum.photos/id/26/800/400",
            "https://picsum.photos/id/27/800/400",
            "https://picsum.photos/id/28/800/400",
            "https://picsum.photos/id/29/800/400",
            "https://picsum.photos/id/30/800/400",
            "https://picsum.photos/id/31/800/400",
            "https://picsum.photos/id/32/800/400",
            "https://picsum.photos/id/33/800/400",
            "https://picsum.photos/id/34/800/400",
            "https://picsum.photos/id/35/800/400",
            "https://picsum.photos/id/36/800/400",
            "https://picsum.photos/id/37/800/400",
            "https://picsum.photos/id/38/800/400",
            "https://picsum.photos/id/39/800/400",
            "https://picsum.photos/id/40/800/400",
            "https://picsum.photos/id/41/800/400",
            "https://picsum.photos/id/42/800/400",
            "https://picsum.photos/id/43/800/400",
            "https://picsum.photos/id/44/800/400",
            "https://picsum.photos/id/45/800/400",
            "https://picsum.photos/id/46/800/400",
            "https://picsum.photos/id/47/800/400",
            "https://picsum.photos/id/48/800/400",
            "https://picsum.photos/id/49/800/400",
            "https://picsum.photos/id/50/800/400",
        ]

        for title,content,img_url in zip(titles,contents,img_urls):
            Post.objects.create(title=title,content=content,img_url=img_url)        
        self.stdout.write(self.style.SUCCESS("Complete Inserting Data"))
